name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Release on Main Branch
        if: github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release on Dev Branch
        if: github.ref == 'refs/heads/dev'
        run: npx semantic-release --no-publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
